### ISSUE TITLE
IllegalStateException when logging in

### ISSUE THREAD

**Issue by chris-ch** [Bombe/Sone#30]
Internal error: please report
java.lang.IllegalStateException: it.sone must not be null
	at net.pterodactylus.sone.template.PostAccessor.get(PostAccessor.kt:44)
	at net.pterodactylus.util.template.TemplateContext.get(TemplateContext.java:271)
	at net.pterodactylus.util.template.TemplateParser$Filters.filter(TemplateParser.java:640)
	at net.pterodactylus.util.template.ConditionalPart$DataCondition.isAllowed(ConditionalPart.java:349)
	at net.pterodactylus.util.template.ConditionalPart.render(ConditionalPart.java:60)
	at net.pterodactylus.util.template.ContainerPart.render(ContainerPart.java:78)
	at net.pterodactylus.util.template.LoopPart.render(LoopPart.java:124)
	at net.pterodactylus.util.template.ContainerPart.render(ContainerPart.java:78)
	at net.pterodactylus.util.template.ConditionalPart.render(ConditionalPart.java:61)
	at net.pterodactylus.util.template.ContainerPart.render(ContainerPart.java:78)
	at net.pterodactylus.util.template.ContainerPart.render(ContainerPart.java:78)
	at net.pterodactylus.util.template.Template.render(Template.java:27)
	at net.pterodactylus.util.template.TemplatePart.render(TemplatePart.java:72)
	at net.pterodactylus.util.template.ContainerPart.render(ContainerPart.java:78)
	at net.pterodactylus.util.template.LoopPart.render(LoopPart.java:124)
	at net.pterodactylus.util.template.ContainerPart.render(ContainerPart.java:78)
	at net.pterodactylus.util.template.ContainerPart.render(ContainerPart.java:78)
	at net.pterodactylus.util.template.Template.render(Template.java:27)
	at net.pterodactylus.sone.web.page.TemplateRenderer.render(TemplateRenderer.kt:13)
	at net.pterodactylus.sone.web.page.FreenetTemplatePage.handleRequest(FreenetTemplatePage.kt:82)
	at net.pterodactylus.sone.web.page.FreenetTemplatePage.handleRequest(FreenetTemplatePage.kt:33)
	at net.pterodactylus.sone.web.page.PageToadlet$handleRequest$1.invoke(PageToadlet.kt:54)
	at net.pterodactylus.sone.web.page.PageToadlet$handleRequest$1.invoke(PageToadlet.kt:36)
	at net.pterodactylus.sone.utils.BucketsKt.use(Buckets.kt:6)
	at net.pterodactylus.sone.web.page.PageToadlet.handleRequest(PageToadlet.kt:52)
	at net.pterodactylus.sone.web.page.PageToadlet.handleMethodGET(PageToadlet.kt:46)
	at freenet.clients.http.ToadletContextImpl.callToadletMethod(ToadletContextImpl.java:741)
	at freenet.clients.http.ToadletContextImpl.handle(ToadletContextImpl.java:678)
	at freenet.clients.http.SimpleToadletServer$SocketHandler.run(SimpleToadletServer.java:1076)
	at freenet.support.PooledExecutor$MyThread.innerRun(PooledExecutor.java:259)
	at freenet.support.PooledExecutor$MyThread.realRun(PooledExecutor.java:197)
	at freenet.support.io.NativeThread.run(NativeThread.java:156)

**Comment by Bombe** [comment]
Hmm, yes, unfortunately there are a number of these exceptions because at some point somewhere a `Sone` reference is disappearing. I haven’t been able to track the reason down for them…

**Comment by chris-ch** [comment]
It occurred indeed right after I deleted a Sone... Not a frequent use case for sure
